name: Sync to Gitee

on:
  push:
    branches:
      - main  # 替换为你的默认分支名称

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Sync to Gitee
        run: |
          git config --global user.name "phimes"
          git config --global user.email "re0phimes@outlook.com"
          git remote add gitee https://gitee.com/Laphirentia/my-spiders.git
          git push gitee HEAD:main

      # TODO: 添加同步步骤
